title: KBG Blog
email: kbgbala@outlook.com
description: >-
  A data scientist's blog on data science, machine learning, and artificial intelligence.
baseurl: "/blog" # Keep empty for user sites, or use "/repositoryname" for project sites
url: "https://github.com/Balagopal-datascientist"
github_username:  Balagopal-datascientist

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Post settings
permalink: /:year/:month/:day/:title/